name: eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install modules
      run: npm i eslint
    - name: Run ESLint
      run: npx eslint --config ./.eslintrc.json . --fix
