name: eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install eslint
    - name: Run ESLint
      with:
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        rules-path: './.eslintrc.json'
        setup-from-package-json: 'true'
